# Welcome to Numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,5,4,6]], np.int8)

In [3]:
myarr[0,1]

5

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int8')

In [6]:
myarr[0,1] = 45

In [7]:
myarr

array([[ 3, 45,  4,  6]], dtype=int8)

# Array Creation: Conversion from other python structures

In [8]:
list_array = np.array([[1,2,3],[5,6,7],[2,1,3]])

In [9]:
list_array.dtype

dtype('int64')

In [10]:
list_array.shape

(3, 3)

In [11]:
list_array.size

9

In [12]:
list_array

array([[1, 2, 3],
       [5, 6, 7],
       [2, 1, 3]])

In [13]:
 np.array({2,3,4,3})

array({2, 3, 4}, dtype=object)

# Zeros

In [14]:
zero = np.zeros((2,5))

In [15]:
zero




array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zero.size

10

In [17]:
zero.shape

(2, 5)

In [18]:
zero.dtype

dtype('float64')

# Range

In [19]:
rng = np.arange(15)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Linspace

In [21]:
lspace = np.linspace(1,50,12)

In [22]:
lspace

array([ 1.        ,  5.45454545,  9.90909091, 14.36363636, 18.81818182,
       23.27272727, 27.72727273, 32.18181818, 36.63636364, 41.09090909,
       45.54545455, 50.        ])

# Empty & Identity

In [23]:
emp = np.empty((4,6))

In [24]:
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
emp_like = np.empty_like(lspace)

In [26]:
emp_like

array([ 1.        ,  5.45454545,  9.90909091, 14.36363636, 18.81818182,
       23.27272727, 27.72727273, 32.18181818, 36.63636364, 41.09090909,
       45.54545455, 50.        ])

In [27]:
ide = np.identity(45)

In [28]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
ide.shape

(45, 45)

# Reshape & Ravel

In [30]:
arr = np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
 arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# Maths

In [34]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [35]:
ar = np.array(x)

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [37]:
ar.sum(axis=0)

array([12,  8,  9])

In [38]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [39]:
ar.T
#for transpose array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [40]:
ar.flat

In [41]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [42]:
ar.ndim
#number of dimentions

2

In [43]:
ar.size

9

In [44]:
ar.nbytes
#total bytes

72

In [45]:
one  = np.array([1,4,500,322,1000,2])

In [46]:
one.argmax()
#at 4th index there is max element

4

In [47]:
one.argmin()

0

In [48]:
one.argsort()
#for sort and array needed indexes

array([0, 5, 1, 3, 2, 4])

In [49]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [50]:
ar.argmin()

8

In [51]:
ar.argmax()

6

In [52]:
ar.argmax(axis=0)

array([2, 1, 1])

In [53]:
ar.argmax(axis=1)

array([2, 2, 0])

In [54]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [55]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [56]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [57]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [58]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [59]:
ar+ar2
#sum of a matrix

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [60]:
ar * ar2
#multiplications of matrix

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [61]:
np.sqrt(ar)
#squareroot of all elements

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [62]:
 ar.sum()

29

In [63]:
ar.min()

0

In [64]:
ar.max()

7

In [65]:
np.where(ar>5)
#return where ar is greter than 5

(array([1, 2]), array([2, 0]))

In [66]:
np.count_nonzero(ar)
#return count of nonzero elements

8

In [67]:
np.nonzero(ar) 

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [68]:
ar[1,2] = 0

In [69]:
np.nonzero(ar) 

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

# size comparison

In [70]:
import sys

In [71]:
py_ar = [0,4,55,2]

In [72]:
np_ar = np.array(py_ar)

In [73]:
sys.getsizeof(1) * len(py_ar)

112

In [74]:
np_ar.itemsize * np_ar.size

32